name: Test and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install frontend dep and lint
        run: |
          cd frontend
          npm install
          npm run lint

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Move dist to backend
        run: |
          rm -rf backend/dist
          mv frontend/dist backend/dist
      
      - name: Install backend dep and lint
        run: |
          cd backend
          npm install
          npm run lint

      - name: Backend tests
        run: | 
          cd backend
          npm test
        env:
          SECRET: ${{ secrets.SECRET }}

  deploy-flyio:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd backend && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-dockerhub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64, linux/amd64

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64, linux/amd64
          push: true
          tags: desipeli/pistepankki:latest
